kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "ibm-ubiquity-db"
  annotations:
    volume.beta.kubernetes.io/storage-class: "STORAGE_CLASS_NAME"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi