apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ubiquity
  labels:
    app: {{ template "ibm_storage_enabler_for_containers.name" . }}
    chart: {{ template "ibm_storage_enabler_for_containers.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - create
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - create
  - patch
