apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "ibm_storage_enabler_for_containers.name" . }}
    chart: {{ template "ibm_storage_enabler_for_containers.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    spec:
      containers:
        - name: hook
          image: byrnedo/alpine-curl
          volumeMounts:
            - name: hook-config
              mountPath: /var/tmp/config
          command: ["/bin/sh"]
          args: ["-c", "/var/tmp/config/post-install.sh"]
      volumes:
        - name: hook-config
          configMap:
            name: hook-config
            defaultMode: 0777
            items:
              - key: post-install
                path: post-install.sh
      restartPolicy: Never
      serviceAccount: ubiquity-helm-hook
  backoffLimit: 1
