{{- if not .Values.spectrumConnect.connectionInfo.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ibm_storage_enabler_for_containers.scbeCredentials" . }}
  namespace: ubiquity
  labels:
    product: ibm-storage-enabler-for-containers
    app: {{ template "ibm_storage_enabler_for_containers.name" . }}
    chart: {{ template "ibm_storage_enabler_for_containers.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
# Spectrum Connect(previously known as SCBE) credentials needed for ubiquity, ubiquity-k8s-provisioner deployments, And ubiquity-k8s-flex daemonset.
type: Opaque
data:
   # Base64-encoded username defined for the IBM Storage Enabler for Containers interface in Spectrum Connect.
   username: {{ .Values.spectrumConnect.connectionInfo.username | b64enc | quote  }}

   # Base64-encoded password defined for the IBM Storage Enabler for Containers interface in Spectrum Connect.
   password: {{ .Values.spectrumConnect.connectionInfo.password | b64enc | quote }}
{{- end }}
