{{- if and (.Values.spectrumConnect) (not .Values.spectrumConnect.backendConfig.dbPvConfig.storageClassForDbPv.existingStorageClass) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ .Values.spectrumConnect.backendConfig.dbPvConfig.storageClassForDbPv.storageClassName  | quote }}
  labels:
    product: ibm-storage-enabler-for-containers
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
{{- if .Values.spectrumConnect.backendConfig.dbPvConfig.storageClassForDbPv.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: "ubiquity/flex"
parameters:
  profile: {{ .Values.spectrumConnect.backendConfig.dbPvConfig.storageClassForDbPv.params.spectrumConnectServiceName  | quote }}
  fstype: {{ .Values.spectrumConnect.backendConfig.dbPvConfig.storageClassForDbPv.params.fsType  | quote }}        # xfs or ext4
  backend: "scbe"
{{- end }}
