apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: ubiquity-db
  labels:
    product: ibm-storage-enabler-for-containers
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubiquity-db
        product: ibm-storage-enabler-for-containers
    spec:
      {{- if .Values.genericConfig.ubiquityDbNodeSelector }}
      nodeSelector:
{{ toYaml .Values.ubiquityDbNodeSelector | indent 8}}
      {{- end }}
      containers:
      - name: ubiquity-db
        image: {{ .Values.images.ubiquitydb }}
        ports:
        - containerPort: 5432
          name: ubiq-db-port  # no more then 15 chars
        env:
          - name: UBIQUITY_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.ubiquityDbCredentials" . }}
                key: username

          - name: UBIQUITY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.ubiquityDbCredentials" . }}
                key: password

          - name: UBIQUITY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.ubiquityDbCredentials" . }}
                key: dbname

        volumeMounts:
          - name: ibm-ubiquity-db
            mountPath: "/var/lib/postgresql/data"
            subPath: "ibm-ubiquity"
{{- if eq .Values.genericConfig.connectionInfo.sslMode "verify-full" }}
          - name: ubiquity-db-private-certificate
            mountPath: /var/lib/postgresql/ssl/private/
{{- end }}

      volumes:
      - name: ibm-ubiquity-db
        persistentVolumeClaim:
          claimName: ibm-ubiquity-db
{{- if (eq .Values.genericConfig.connectionInfo.sslMode "verify-full") }}
      - name: ubiquity-db-private-certificate
        secret:
          secretName: ubiquity-db-private-certificate
          items:
          - key: ubiquity-db.key
            path: ubiquity-db.key
            mode: 0600
          - key: ubiquity-db.crt
            path: ubiquity-db.crt
            mode: 0600
{{- end }}
