kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "ubiquity-claim"
  annotations:
    volume.beta.kubernetes.io/storage-class: "ubiquity-spectrum-scale"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi