kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: "ubiquity-spectrum-scale"
  annotations:
   storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: "ubiquity/flex"
parameters:
  filesystem: "gold"