kind: Pod
apiVersion: v1
metadata:
  name: write-pod-test
spec:
  containers:
  - name: write-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: ubiquity-pvc 
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: ubiquity-pvc
      persistentVolumeClaim:
        claimName: ubiquity-claim
