kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "SCBE_acceptance_volume1"
  annotations:
    volume.beta.kubernetes.io/storage-class: "gold"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi