kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "PVCNAME"
  annotations:
    volume.beta.kubernetes.io/storage-class: "PROFILE"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: SIZE